branches:
  only:
    - master

language: python
python:
  - "2.7"
  - "3.4"
  - "nightly"

install:
  - pip install -U -r test_requirements.txt --use-mirrors

before_script:
  - pip install -e . --use-mirrors
script:
  - py.test tests --doctest-modules --pep8 coveralls -v --cov coveralls --cov-report term-missing
after_success:
  - coveralls

